# URLS TO DATA

SAMPLE_IDS:
  - PAW70337
  # - PAW71238

# graph_base: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v1.1-mc-chm13.d9"
# graph_snarl: "/private/groups/migalab/shnegi/vg_anchors_project/graphs/hprc-v1.1-mc-chm13.d9.snarls"

# ############# V2 frequency filtered graphs ################
# graph_base: "/private/home/ghickey/dev/work/hprc-v2.0-feb28/hprc-v2.0-mc-chm13-eval/hprc-v2.0-mc-chm13-eval.d46"
# graph_snarl: "/private/groups/migalab/shnegi/vg_anchors_project/graphs/hprc-v2.0-mc-chm13-eval.d46.snarls"

############ V2 normal graph for haplotype-sampling ################
graph_base: "/private/groups/cgl/hprc-graphs/hprc-v2.0-feb28/hprc-v2.0-mc-chm13-eval/hprc-v2.0-mc-chm13-eval"

############ V2 normal graph with HG002 assembly included, to be used as a positive control ################
graph_base_hg2: "/private/groups/cgl/hprc-graphs/hprc-v2.0-feb28/hprc-v2.0-mc-chm13/hprc-v2.0-mc-chm13"
# graph_snarl: "/private/groups/cgl/hprc-graphs/hprc-v2.0-feb28/hprc-v2.0-mc-chm13-eval/hprc-v2.0-mc-chm13-eval.snarls" # use only when doing full v2 graph mapping

minparams: "k31.w50.W"
chm13_ref: "/private/groups/migalab/references/CHM13/chm13v2.0.fa"
HG002v101_ref: "/private/groups/migalab/kkyriaki/references/unziped/hg002v1.0.1.fasta"

MINIMAP:
  kmerSize: 17
  minibatchSize: "5G"
  mdString: ""  # other option "--MD"
  eqxString: "--eqx"  # if not, then ""
  asmPreset: "asm10"

HAPLOTYPE_SAMPLING:
  k: 29
  m: 128
  v: 2
  num_haps: 16
  diploid_sampling: False

ANALYSEPAF:
  bin: "/private/groups/migalab/shnegi/vg_anchors_project/analyzePaf"

DISPLAYPAF:
  bin: "/private/groups/migalab/shnegi/vg_anchors_project/DisplayPafAlignments"

SHASTA:
  bin: "/private/groups/migalab/shnegi/vg_anchors_project/shasta"
  conf: "/private/groups/migalab/shnegi/vg_anchors_project/anchors.conf"

TMPDIR: "/private/groups/migalab/shnegi/vg_anchors_project/test_lr_giraffe_assembly/tmp"

# Control which part of the workflow to run.
RUN_MODE: "no_positive_control"       # "no_positive_control" | "positive_control_only"
READ_TYPE: "raw"                       # Controls whether to use error corrected reads or raw reads

RUN_GBZ_QUERY: True               # If True, run gbz query for subgraph extraction (pg.vg, dist, gaf)
USE_FULL_GRAPH: False             # If True, use full graph for anchor generation and gbz queried reads and index. NOTE: This will overwrite the anchors/ directory.
RUN_DEBUGGING: False         # If True, generate all debugging output files (reliable snarls files, bandage debugging files, etc.)

slurm_extra: "--exclude=phoenix-[00-10,22-24]"
exclusive_timing: true

####### REGIONS TO ASSEMBLE ########
region:
  chromosome: "chr22"
  start: "21775882"
  end: "22130996"
  flank: 5000000
region_id: "HIC2"
