# URLS TO DATA

SAMPLE_IDS:
  - PAW70337
  - PAW71238


# --- Paths to data ---
raw_reads_dir: "/path/to/your/raw/reads/"


# --- Path to scripts ---
scripts_dir: "workflow/scripts"


# --- Paths to Reference Genomes and Graphs ---
# These paths should be updated to point to the location of the files on your system.
############ HPRC V2 graph for haplotype-sampling ################
graph_base: "/path/to/your/hprc-v2.0-mc-chm13-eval"
############ V2 graph with HG002 assembly included, to be used as a positive control ################
graph_base_hg2: "/path/to/your/hprc-v2.0-mc-chm13"
minparams: "k31.w50.W"


# --- Reference genome paths ---
chm13_ref: "/path/to/your/chm13v2.0.fa"
HG002v101_ref: "/path/to/your/hg002v1.0.1.fasta"


# --- Minimap2 configuration ---
MINIMAP:
  kmerSize: 17
  minibatchSize: "5G"
  mdString: ""  # other option "--MD"
  eqxString: "--eqx"  # if not, then ""
  asmPreset: "asm10"


# --- Haplotype sampling configuration ---
HAPLOTYPE_SAMPLING:
  k: 29
  m: 128
  v: 2
  num_haps: 16
  diploid_sampling: False


# --- vg-anchors configuration ---
vg-anchors_config: "workflow/vg-anchors/config.ini"


# --- Tool Configuration ---
ANALYSEPAF:
  bin: "workflow/shasta/analyzePaf"
DISPLAYPAF:
  bin: "workflow/shasta/DisplayPafAlignments"
SHASTA:
  bin: "workflow/shasta/shasta"
  conf: "workflow/shasta/anchors.conf"


# --- Setup the temporary directory ---
TMPDIR: "../tmp"  # Or change to your desired temporary directory for intermediate files


# --- Run mode and read type ---
    # Control which part of the workflow to run.
    #   "no_positive_control": Runs only the sample workflow.
    #   "positive_control_only": Runs only the positive control workflow.
RUN_MODE: "no_positive_control"
    # Controls whether to use error corrected "ec" reads or "raw" reads for assembly
READ_TYPE: "raw"


# --- Region to assemble ---
region:
  chromosome: "chr16"
  start: "2160175"
  end: "3022916"
  flank: 1000000
region_id: "PDPK"
